server:
  port: 9999
  
spring:  datasource:    username: system
    password: manager
    url: jdbc:oracle:thin:@localhost:1521:xe
    driver-class-name: oracle.jdbc.driver.OracleDriver
  mvc:    view:      prefix: /views/
      suffix: .jsp
      
  jpa:    hibernate:      ddl-auto: update